[package]
name = "wakatime-zed"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "wakatime/src/lib.rs"
crate-type = ["cdylib"]

[workspace]
members = ["wakatime-ls", "wakatime"]
